import Cards from "./Components/Cards"
import './App.css'


const App = () => {
   const data = [
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/12.jpg",
    "name": "Aisha Kapoor",
    "post": "UI Designer",
    "followers": 12500,
    "project": "Mobile Banking App",
    "city": "Mumbai",
    "about": "Creative designer focused on crafting intuitive mobile experiences.",
    "skill1": "Figma",
    "skill2": "Sketch",
    "skill3": "Adobe XD",
    "skill4": "Illustrator",
    "skill5": "User Research"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/32.jpg",
    "name": "Rahul Verma",
    "post": "Frontend Developer",
    "followers": 8900,
    "project": "E-commerce Platform",
    "city": "Bengaluru",
    "about": "Frontend engineer specializing in modern JavaScript frameworks.",
    "skill1": "React",
    "skill2": "Vue.js",
    "skill3": "HTML5",
    "skill4": "CSS3",
    "skill5": "Tailwind CSS"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/24.jpg",
    "name": "Sara Almeida",
    "post": "UX Researcher",
    "followers": 6400,
    "project": "Travel Booking Portal",
    "city": "Goa",
    "about": "Driven researcher uncovering pain points and insights to inform design.",
    "skill1": "User Research",
    "skill2": "Personas",
    "skill3": "Journey Mapping",
    "skill4": "Figma",
    "skill5": "Data Analysis"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/54.jpg",
    "name": "Aditya Rao",
    "post": "Backend Engineer",
    "followers": 5800,
    "project": "Inventory Management System",
    "city": "Hyderabad",
    "about": "Backend developer with a passion for cloud architecture and APIs.",
    "skill1": "Node.js",
    "skill2": "Express",
    "skill3": "MongoDB",
    "skill4": "AWS",
    "skill5": "Docker"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/35.jpg",
    "name": "Elena Sharma",
    "post": "Product Manager",
    "followers": 9400,
    "project": "Health App",
    "city": "Delhi",
    "about": "Leads product vision and strategy to drive user engagement.",
    "skill1": "Roadmapping",
    "skill2": "Stakeholder Management",
    "skill3": "Agile",
    "skill4": "Figma",
    "skill5": "Jira"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/89.jpg",
    "name": "Vikram Sethi",
    "post": "Mobile App Developer",
    "followers": 7200,
    "project": "Social Network App",
    "city": "Pune",
    "about": "Creates high‑performance mobile apps for Android and iOS.",
    "skill1": "Flutter",
    "skill2": "React Native",
    "skill3": "Firebase",
    "skill4": "Java",
    "skill5": "Kotlin"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/47.jpg",
    "name": "Nisha Pillai",
    "post": "Graphic Designer",
    "followers": 11200,
    "project": "Brand Identity Revamp",
    "city": "Chennai",
    "about": "Creates visual stories that bring brand identities to life.",
    "skill1": "Photoshop",
    "skill2": "Illustrator",
    "skill3": "InDesign",
    "skill4": "Typography",
    "skill5": "Logo Design"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/23.jpg",
    "name": "Karan Mehta",
    "post": "Data Analyst",
    "followers": 5200,
    "project": "Sales Analytics Dashboard",
    "city": "Ahmedabad",
    "about": "Transforms data into visual insights that drive business decisions.",
    "skill1": "Power BI",
    "skill2": "SQL",
    "skill3": "Python",
    "skill4": "Excel",
    "skill5": "Tableau"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/58.jpg",
    "name": "Priya Nair",
    "post": "Content Strategist",
    "followers": 7700,
    "project": "SEO‑Optimized Blog Campaign",
    "city": "Kochi",
    "about": "Builds words and strategies that connect audiences with brands.",
    "skill1": "Copywriting",
    "skill2": "SEO",
    "skill3": "Content Marketing",
    "skill4": "CMS",
    "skill5": "Analytics"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/45.jpg",
    "name": "Arjun Das",
    "post": "Full Stack Developer",
    "followers": 13300,
    "project": "Learning Management System",
    "city": "Delhi",
    "about": "Develops full‑stack web applications with modern technologies.",
    "skill1": "React",
    "skill2": "Node.js",
    "skill3": "MySQL",
    "skill4": "Git",
    "skill5": "AWS"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/65.jpg",
    "name": "Meera Joshi",
    "post": "Illustrator",
    "followers": 9100,
    "project": "Children’s Book Artwork",
    "city": "Jaipur",
    "about": "Brings characters and stories to life through vibrant illustrations.",
    "skill1": "Illustrator",
    "skill2": "Procreate",
    "skill3": "Photoshop",
    "skill4": "Color Theory",
    "skill5": "Storyboarding"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/70.jpg",
    "name": "Ravi Malhotra",
    "post": "DevOps Engineer",
    "followers": 4800,
    "project": "Cloud Deployment Platform",
    "city": "Noida",
    "about": "Ensures continuous deployment pipelines and efficient infrastructure.",
    "skill1": "Kubernetes",
    "skill2": "Terraform",
    "skill3": "AWS",
    "skill4": "CI/CD",
    "skill5": "Shell Scripting"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/80.jpg",
    "name": "Ananya Deshpande",
    "post": "Motion Designer",
    "followers": 9900,
    "project": "Animated Product Ads",
    "city": "Nashik",
    "about": "Creates smooth, engaging motion designs for digital platforms.",
    "skill1": "After Effects",
    "skill2": "Premiere Pro",
    "skill3": "Cinema 4D",
    "skill4": "Storyboard",
    "skill5": "Sound Design"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/15.jpg",
    "name": "Yusuf Khan",
    "post": "Cybersecurity Specialist",
    "followers": 5400,
    "project": "Enterprise Security Framework",
    "city": "Lucknow",
    "about": "Protects business systems through proactive threat analysis.",
    "skill1": "Network Security",
    "skill2": "Ethical Hacking",
    "skill3": "Firewalls",
    "skill4": "Python",
    "skill5": "Penetration Testing"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/18.jpg",
    "name": "Ritika Mal",
    "post": "UI/UX Designer",
    "followers": 12800,
    "project": "SaaS Dashboard Design",
    "city": "Chandigarh",
    "about": "Designs elegant user interfaces that empower SaaS experiences.",
    "skill1": "Figma",
    "skill2": "User Flows",
    "skill3": "Prototyping",
    "skill4": "Adobe XD",
    "skill5": "Design Systems"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/27.jpg",
    "name": "Harish Gupta",
    "post": "Cloud Architect",
    "followers": 6600,
    "project": "Scalable Cloud Platform",
    "city": "Nagpur",
    "about": "Designs and manages reliable and scalable cloud‑based systems.",
    "skill1": "AWS",
    "skill2": "Azure",
    "skill3": "Docker",
    "skill4": "Kubernetes",
    "skill5": "Security"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/9.jpg",
    "name": "Divya Bansal",
    "post": "Brand Strategist",
    "followers": 8800,
    "project": "Rebranding Campaign",
    "city": "Indore",
    "about": "Helps brands find their voice and connect with target audiences.",
    "skill1": "Market Research",
    "skill2": "Brand Positioning",
    "skill3": "Campaign Planning",
    "skill4": "Storytelling",
    "skill5": "Copywriting"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/12.jpg",
    "name": "Tanish Roy",
    "post": "Game Designer",
    "followers": 7200,
    "project": "Action RPG Game",
    "city": "Kolkata",
    "about": "Designs immersive game worlds and engaging player experiences.",
    "skill1": "Unity",
    "skill2": "C#",
    "skill3": "Blender",
    "skill4": "Level Design",
    "skill5": "UI Design"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/30.jpg",
    "name": "Neha Singh",
    "post": "Digital Marketer",
    "followers": 10100,
    "project": "Ad Campaign Optimization",
    "city": "Mumbai",
    "about": "Optimizes digital campaigns for engagement and ROI.",
    "skill1": "Google Ads",
    "skill2": "Facebook Ads",
    "skill3": "Content Strategy",
    "skill4": "Analytics",
    "skill5": "Copywriting"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/men/90.jpg",
    "name": "Manish Patel",
    "post": "AI Engineer",
    "followers": 8700,
    "project": "Chatbot Integration System",
    "city": "Surat",
    "about": "Builds smart systems powered by machine learning and NLP.",
    "skill1": "Python",
    "skill2": "TensorFlow",
    "skill3": "PyTorch",
    "skill4": "Machine Learning",
    "skill5": "API Integration"
  },
  {
    "profileImageUrl": "https://randomuser.me/api/portraits/women/75.jpg",
    "name": "Simran Kaur",
    "post": "Web Designer",
    "followers": 9500,
    "project": "Restaurant Website Redesign",
    "city": "Amritsar",
    "about": "Creates user-friendly responsive websites with strong aesthetics.",
    "skill1": "HTML",
    "skill2": "CSS",
    "skill3": "JavaScript",
    "skill4": "Figma",
    "skill5": "Responsive Design"
  }
]
  return (
    <div className="cards-container">
      {data.map((profile, index) => (
        <Cards key={index} profile={profile} />
      ))}
    </div>
  )
}

export default App